services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_pass
      MYSQL_ROOT_HOST: '%'
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

  php:
    build:
      context: ./docker/php-fpm
    container_name: php
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./:/var/www/html
    networks:
      - app-network
    command: >
      sh -c "
      if [ ! -d vendor ]; then
        composer install
      fi &&
      php-fpm
      "

  nginx:
    image: nginx:alpine
    container_name: nginx
    depends_on:
      php:
        condition: service_started
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html
    networks:
      - app-network

volumes:
  mysql_data:
    driver: local

networks:
  app-network:
    driver: bridge